name: scentlaundry
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  get: ^4.6.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  map_location_picker: ^1.2.8+3
  contactus: ^1.2.3
  date_picker_timeline: ^1.2.5
  awesome_dialog: ^3.1.0
  flutter_easyloading: ^3.0.5
  http: ^1.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  geocoding: ^2.1.1
  lottie: ^2.7.0
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: reg
      fonts:
        - asset: assets/font/Roboto/Roboto-Regular.ttf
    - family: Inter bold
      fonts:
        - asset: assets/font/Roboto/Roboto-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/font/Roboto/Roboto-Medium.ttf
flutter_intl:
  enabled: true
  localizely:
    project_id: "1"
